

```{r}
library(shiny)
library(tidyverse)
```

```{r}
idaho_2020 <- read.csv('../data/state_ID.csv')
```

```{r}
dim(idaho_2020)
```

```{r}
head(idaho_2020)
```
```{r}
str(idaho_2020)   # TO SEE DATA TYPES OF COLUMNS
```
```{r}
# SEE KANBAN BOARD AT https://github.com/nss-data-science-cohort-5/hmda_shiny-crazy-eights/projects/1
```

Part 1
Explore the HMDA dataset (https://ffiec.cfpb.gov/data-browser/data/2020?category=nationwide)

Specifically for the North West region

Focus on finding data that can be used to understand:

demographic makeup of a region
including ethnicity/race
gender
age
disability
familial status
approved loans
loan type
dwelling category
income
```{r}
# TO DO - Show what percentage and # of loans were applied for by disability
#     BUT WHAT IS DISABILITY FIELD?
```

```{r}
# TO DO - Show what percentage and # of loans were applied for by age

idaho_2020 %>%
  group_by(applicant_age) %>%
  summarise(age_row_ct = n()
          #  , over_62_pct = over_62_rows / rowSums() * 100
          ) %>%
  arrange(desc(age_row_ct)) %>%
  ungroup()
```

```{r}
# NORMALIZE PERCENTAGES OF APPLICANTS OVER 62, etc.
idaho_2020 %>%
  group_by(applicant_age_above_62) %>%
  summarise(over_62_rows = n()) %>%
  ungroup()
```

```{r}
# TO DO - Show what percentage and # of loans were applied for by gender
idaho_2020 %>%
  group_by(applicant_sex) %>%
  summarise(sex_row_ct = n()) %>%
  arrange(desc(sex_row_ct)) %>%
  ungroup()
```
```{r}
idaho_2020 %>%
  group_by(applicant_sex_observed) %>%
  summarise(appl_sex_row_ct = n()) %>%
  arrange(desc(appl_sex_row_ct)) %>%
  ungroup()
```

```{r}
# TO DO - Show what percentage and # of loans were applied for by race
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  summarise(appl_race_rows = n()) %>%
  arrange(desc(appl_race_rows)) %>%
  ungroup()
```
```{r}
idaho_2020 %>%
  group_by(derived_race) %>%
  summarise(derived_race_rows = n()) %>%
  arrange(desc(derived_race_rows)) %>%
  ungroup()
```

```{r}
# TO DO - Select a lending institution by its LEI, and be able to select a subset of peer institutions based on geographical area (County, State, MSA/Census Tract)
```

```{r}
# TO DO - Table and visual showing select LEI compared to selected geographical area (County, State, or MSA/Census Tract)
```

```{r}
# TO DO - Filter by lender (Legal Entity Identifier or LEI)
```

```{r}
# TO DO - Filter by geographical area (County, State, or MSA/Census Tract)
```

```{r}
```

```{r}
# COUNT ROWS OF LEI / NORMALIZE PERCENTAGES

idaho_2020 %>%
  group_by(lei) %>%
  summarise(lei_rows = n()) %>%
  arrange(desc(lei_rows)) %>%
  ungroup()
```

```{r}
# WHERE IS LOOKUP TABLE / VALUES OF RACE CODES? 

# SEE https://ffiec.cfpb.gov/documentation/2020/lar-data-fields/#derived_race -
# WILL WANT USER TO BE ABLE TO SELECT YEAR TO SCRAPE MAPPINGS
```

```{r}
# CREDIT SCORES ABOVE OR BELOW CUTOFFS, e.g. 700 (WHAT ARE CURRENT CRITERIA?)

# TO DO - THIS WOULD BE MORE USEFUL AS A PIVOTED OR ROWWISE FUNCTION
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  # view()
  summarize(med_race_cred = median(applicant_credit_score_type,
                                   na.rm = TRUE)) %>%
  ungroup()
```

```{r}

# 2021 CREDIT SCORE RANGES - 

# FICO 300-579 = POOR; 580-669 = FAIR; 670-739 = GOOD; 740-799 = VERY GOOD; 800-850 = EXCELLENT
# FROM smartasset.com/credit-cards/what-are-the-credit-score-ranges
idaho_2020 %>%
  group_by(derived_ethnicity) %>%
  # view()
  summarize(med_ethn_cred = median(applicant_credit_score_type,
                                   na.rm = TRUE)) %>%
  ungroup()
```

```{r}
idaho_2020 %>%
  distinct(derived_ethnicity)
```

```{r}
# ARE LTVs AND DEBT-TO-INCOME RATIOS FOR MINORITIES DIFFERENT?  HOW DO LTVs VARY AMONG MSAs?

     # CAN PIPE INTO view() AND SORT BY COLUMNS TO SEE VALUES - e.g. rate_spread CONTAINS 'Exempt'

# TURN rate_spread INTO numeric COLUMN TO GET AGGREGATES?

idaho_2020 %>%
  group_by(derived_ethnicity) %>%
  filter(rate_spread != 'Exempt') %>%
  # view()
  summarize(med_ethn_rate_sprd = median(as.double(rate_spread,
                                        na.rm = TRUE))) %>%
  arrange(desc(med_ethn_rate_sprd)) %>%
  ungroup()
```

```{r}
# TURN rate_spread INTO numeric COLUMN TO GET AGGREGATES?

idaho_2020 %>%
  filter(rate_spread != 'Exempt') %>%
  group_by(applicant_race.1) %>%
  summarize(med_race_rate_sprd = median(as.double(rate_spread,
                                        na.rm = TRUE))) %>%
  arrange(desc(med_race_rate_sprd)) %>%
  ungroup()
```

```{r}
# ARE INTEREST RATES DIFFERENT ON SAME LTVs FOR DIFFERENT RACES?  RATE SPREAD?
# ORIGINATION FEES, DISCOUNT POINTS, NEGATIVE AMORTIZATION, INTEREST-ONLY PAYMENTS,
# BALLOON PAYMENTS, ...

idaho_2020 %>%
  group_by(derived_ethnicity) %>%
  summarize(med_ethn_ltv = median(loan_to_value_ratio,
                                       na.rm = TRUE)) %>%
  arrange(desc(med_ethn_ltv)) %>%
  ungroup()
```

```{r}
# DTI COLUMN HAS A LOT OF "30%-<36%" CHARACTERS IN IT - USE like() / filter() / grepl()?
# wacky_dti <- 
idaho_2020 %>%
  filter(debt_to_income_ratio %in% '%')
```
```{r}
# USE rowwise() OR pivot_longer() FOR denial_reason AND RACE / SEX / AGE?
```

```{r}
idaho_2020 %>%
  group_by(derived_ethnicity) %>%
  summarize(median_dti = median(as.double(debt_to_income_ratio,
                                na.rm = TRUE))) %>%
  ungroup()
```
```{r}
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  summarize(med_orig = median(as.double(origination_charges,
                                        na.rm = TRUE))) %>%
  ungroup()
```


```{r}
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  summarize(med_points = median(as.double(discount_points,
                                          na.rm = TRUE))) %>%
  ungroup()
```


```{r}
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  summarize(med_neg_am = median(as.double(negative_amortization,
                                          na.rm = TRUE))) %>%
  ungroup()
```
```{r}
idaho_2020 %>%
  group_by(applicant_race.1) %>%
  summarize(med_balloon = median(as.double(balloon_payment,
                                           na.rm = TRUE))) %>%
  ungroup()
```

```{r}
# COULD MAKE TIBBLE OF ONLY NON-NULLS, etc, THEN JOIN?

idaho_2020 %>%
  # drop_na(applicant_race.1) %>%
  group_by(applicant_race.1 #, na.rm = TRUE) %>%
          ) %>%
  summarize(median_dti = median(debt_to_income_ratio,
                                na.rm = TRUE)) %>%
  ungroup()
```

```{r}
idaho_2020 %>%
  distinct(applicant_race.1) %>%
  drop_na()
```

```{r}
rlang::last_trace()
```


